# Generated by Django 2.2.13 on 2020-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcounter',
            name='name',
            field=models.CharField(default='count', max_length=10),
            preserve_default=False,
        ),
    ]
